### ISSUE TITLE
7.4.1194 キャッチアップに伴う新規の文を翻訳する

### ISSUE THREAD

**Issue by koron** [vim-jp/vimdoc-ja#164]
#163 の残件です。対象となるファイルは以下のとおりです。
やれる人がやれるときに随時翻訳してもらえると嬉しいです。

----

以上は変更点が100行未満なので、翻訳しやすいはず。

* [x] doc/autocmd.jax (@rhysd, #166)
* [x] doc/change.jax (@rhysd, #183)
* [x] doc/develop.jax (@rhysd, #167)
* [x] doc/editing.jax (@rhysd, #168)
* [x] doc/fold.jax (@rhysd, #169)
* [x] doc/hangulin.jax (@rhysd, #170)
* [x] doc/if_lua.jax    # 100行超えたけど、内容的に大したことない (@rhysd, #189)
* [x] doc/if_mzsch.jax (@rhysd, #175)
* [x] doc/if_perl.jax (@rhysd, #174)
* [x] doc/if_pyth.jax (@rhysd, #173)
* [x] doc/if_ruby.jax (@rhysd, #172)
* [x] doc/if_tcl.jax (@rhysd, #174)
* [x] doc/insert.jax (@rhysd, #184)
* [x] doc/map.jax (@rhysd, #165)
* [x] doc/netbeans.jax (@mattn, #193)
* [x] doc/pattern.jax (@h-east https://github.com/vim-jp/vimdoc-ja/commit/739006bf724c8eeda8f5b40cd15c2e7f9aa49eac)
* [x] doc/pi_logipat.jax # 別件で英語だけ反映されていた (@mattn, #177)
* [x] doc/quickref.jax (@rhysd , #185)
* [x] doc/repeat.jax (@thinca, #182)
* [x] doc/spell.jax (#65 で継続的に翻訳する)
* [x] doc/tagsrch.jax (@rhysd #199)
* [x] doc/term.jax (@koron)
* [x] doc/usr_02.jax (vim-jp と愉快な仲間たち #201)
* [x] doc/usr_03.jax (@mattn, #180)
* [x] doc/usr_41.jax (@rbtnnさん, #171)
* [x] doc/various.jax (@mattn, #179, #192)

こっから先は100行超えるので、嫌。

* [x] doc/eval.jax (@rbtnnさん, #176)
* [x] doc/options.jax (@h-east さん, @mattn #200)
* [x] doc/pi_netrw.jax  # 地獄 (@tyru さん)
* [x] doc/syntax.jax (@mattn, #196)
* [x] doc/windows.jax (@mattn, #195)

----

各ファイルの差分を調べるには、例えば doc/eval.jax ならば

    git diff f8de019^ f8de019 -- doc/eval.jax

みたいにしてください。キャッチアップ時にどこに英語が残ってるかとか、どこを翻訳したかがわかります。

**Comment by thinca** [comment]
翻訳作業に可能な限り協力したいのですが、これは個別で PR 出していく感じで良いでしょうか?

**Comment by crazymaster** [comment]
権限を持っている人は直接コミットでいいじゃないですかね。

**Comment by koron** [comment]
権限あるなら直接でいいですよ～。

可能なら
  https://github.com/vim-jp/vimdoc-ja/blob/devel/catchup-7.4.1194.md#英文だけは反映済み
このリストから
  https://github.com/vim-jp/vimdoc-ja/blob/devel/catchup-7.4.1194.md#完訳
こっちに移すのも、一緒にコミットして貰えると嬉しいです。

あと他の人が被らないように、作業開始時に、ここで宣言してくれると良いかもです。

**Comment by thinca** [comment]
翻訳のレビューを受けたいなーと思ったんですが、興味ある人がコミットを直接見て問題があったら指摘(もしくは直す)みたいな感じですかね?

**Comment by koron** [comment]
あ、PRだしてくれればレビューしますよ。

**Comment by thinca** [comment]
了解です！

**Comment by h-east** [comment]
doc/pattern.jax やります。

**Comment by koron** [comment]
あ、キャッチアップに伴う変更箇所を調べるには、たとえば doc/eval.jax なら

    git diff f8de019^ f8de019 -- doc/eval.jax

とかすると便利です。トップにも追記しておきます。

**Comment by h-east** [comment]
私はLast commitの差分はこんな感じでやってました。
```
git log -1 -p -- doc/eval.jax
```

**Comment by rbtnn** [comment]
「doc/usr_41.jax」やってみます。

**Comment by h-east** [comment]
初めてやる人や久しぶりにやる人は、ひと通り wiki には目を通した方がいいかもしんない
https://github.com/vim-jp/vimdoc-ja/wiki

Vim ドキュメント翻訳者の手引き
https://github.com/vim-jp/vimdoc-ja/wiki/Guide

**Comment by koron** [comment]
ごめん、目を通さずやっちゃった (・ω<)

**Comment by rhysd** [comment]
@h-east ポインタありがとうございます．

とりあえず3つぐらいやってみました．

**Comment by koron** [comment]
しまったな…ファイルリストの修正、マージすると絶対コンフリクトしそうw

**Comment by crazymaster** [comment]
訳し終わったやつをファイルリストから消すだけにするとか？

**Comment by koron** [comment]
まぁ、もうしょうがないですw しこしこと解消していきましょ

**Comment by rbtnn** [comment]
「doc/usr_41.jax」やったし、「doc/eval.jax」やってみます。

> まぁ、もうしょうがないですw しこしこと解消していきましょ

今後も

> 権限あるなら直接でいいですよ～。
> 
> 可能なら翻訳しおわったファイルは
> https://github.com/vim-jp/vimdoc-ja/blob/devel/catchup-7.4.1194.md#英文だけは反映済み
> このリストから
> https://github.com/vim-jp/vimdoc-ja/blob/devel/catchup-7.4.1194.md#完訳
> こっちに移すのも、一緒にコミットして貰えると嬉しいです。
> 
> あと他の人が被らないように、作業開始時に、ここで宣言してくれると良いかもです。

このやり方で治しちゃっていい感じですか？

**Comment by koron** [comment]
いいです。コンフリクトは私の方で解消しますので。

**Comment by rbtnn** [comment]
了解です。

**Comment by crazymaster** [comment]
そういえば、pi_logipat.txt忘れてる

**Comment by koron** [comment]
え? `*.txt` でコピーしたのに…なんで?

**Comment by crazymaster** [comment]
いや、既に反映済みだったのを思い出しただけです

**Comment by h-east** [comment]
doc/pattern.jax Upしました。
https://github.com/vim-jp/vimdoc-ja/commit/739006bf724c8eeda8f5b40cd15c2e7f9aa49eac

直接develを弄ったけどちゃんとcommit/pushいけてる？
(次からはPRにします)

**Comment by koron** [comment]
@h-east 私の方からは2点だけコメントを付けておきました (｀･ω･´)ゞ

**Comment by h-east** [comment]
@koron Thanks! 修正しました。https://github.com/vim-jp/vimdoc-ja/commit/301f9a2025a1aa09e8a11919d53e546c6731ea39

**Comment by crazymaster** [comment]
さっそくchannel.txtに更新がかかっている件について
https://github.com/vim/vim/commit/fb1f62691eae7c79a28b3b17a60e72ce198c71a2

**Comment by koron** [comment]
channel.txt は 1194 とは別口で翻訳を突っ込んだので、適宜更新してもらえれば。

**Comment by mattn** [comment]
windows.jax 意外と差分少ないね。(やるとは言ってない)

**Comment by crazymaster** [comment]
various.jax はまだ完全には終わっていないのでは

**Comment by koron** [comment]
あら? そうなの? 戻しておいてもらえますか?

**Comment by koron** [comment]
あ、チェックだけは外しておきます。

**Comment by crazymaster** [comment]
そもそもファイルリストで完訳の方に移してないですね

**Comment by tyru** [comment]
> doc/pi_netrw.jax # 地獄

登ってやるぜ、この地獄坂をよ…！

![次回作にご期待ください](http://cdn-ak.f.st-hatena.com/images/fotolife/K/Kei-Type46/20101027/20101027232137.gif)

一応確認ですが、このスレではとりあえずVim 7.4.1194の`*.txt`を元に翻訳すれば良いんですよね。

**Comment by koron** [comment]
@tyru ええ。以下で、追加(&削除)された文だけ、確認もできますよ。

    git diff f8de019^ f8de019 -- doc/pi_netrw.jax

**Comment by tyru** [comment]
@koron ありがとうございます！
さっそく `:help netrw-c-tab` がnetrwバッファで使えなかったりしてﾎﾟｶｰﾝ状態なのですが、こういう質問とかってここでしちゃって大丈夫ですか？
それとも別にissueかPR(途中でコミット？)立てた方がいいでしょうか。

**Comment by koron** [comment]
好きにしたらエエですよ。
まぁ、個人的にはそのファイルは、理解やverifyしようとせずにまずは訳しちゃったほうが良いかな、って思ってますw

**Comment by tyru** [comment]
了解です！＞まずは訳す

**Comment by mattn** [comment]
ひそかに doc/spell.jax も未翻訳があるのでトリプルAクラスだ。。。

**Comment by k-takata** [comment]
spell.jax は #65 で何年もかけてゆるゆるやってますからね。ここで一気にやるというのもありか？
\# やるとは言っていない。

**Comment by mattn** [comment]
大変ならパラグラフで分担するってのもアリかもですね。
\# やるとは言っていない。

**Comment by k-takata** [comment]
spell.jax の後半はファイルフォーマットの説明なので、ふつーに使うにはいらんでしょという気もしますが。

**Comment by utamaro** [comment]
横から失礼いたします。mattnさんのtwitter見て少し興味をもちまして
＃やるとは言っていない。
で、transifexとかの翻訳プラットフォームは使われないんですか？
これだけ人が多いと管理が大変かと、、、。
翻訳でもVimだけを使うことににこだわりを持たれてるんだったら、すいません。。

**Comment by k-takata** [comment]
transifexについては #157 を参照してください。
今のところ、移行しようという決め手に欠ける感じです。

**Comment by h-east** [comment]
`doc/options.jax` やります。

**Comment by h-east** [comment]
同じ間違いをして偶然typoを見つけてしまった:grin:
https://github.com/vim-jp/vimdoc-ja/blob/devel/doc/options.jax#L74
https://github.com/vim-jp/vimdoc-ja/blob/devel/doc/options.jax#L4351
s/規定/既定/

**Comment by h-east** [comment]
`doc/options.jax` ちょびっとだけ翻訳しました。一旦手放します。やれる人いたらお願いします。
https://github.com/vim-jp/vimdoc-ja/pull/200

optionsブランチをそのまま使って頂いて構いません。
https://github.com/vim-jp/vimdoc-ja/tree/options

**Comment by mattn** [comment]
* doc/spell.jax
* doc/usr_02.jax
* doc/pi_netrw.jax

残が以上の様ですが、どなたか着手中の方いますか？

* 「翻訳やりかけ」
* 「翻訳やりたい」
* 「翻訳やらせろ」
* 「わーい翻訳、あかり翻訳だーいすきー」

等の状況を教えて貰えると助かります。

**Comment by rhysd** [comment]
僕は手元に作業中のものはもう無いです :muscle: 

pi_netrw.jax は @tyru さんが作業されていたような…

**Comment by tyru** [comment]
@mattn はい、pi\_netrw.jaxは自分がやってます。進捗率は(`r!git diff ...` したスクラッチバッファのファイル中での位置の%表示を信じるなら)60%位だったと思います。
今日は私用で帰るの遅くなりそうですが、帰宅次第別ブランチに途中経過をpushしておきます。

**Comment by mattn** [comment]
あざます。空き確認の為に↑のでアサインさせてもらいますね。

**Comment by tyru** [comment]
了解です。

**Comment by tyru** [comment]
@mattn [pi\_netrw](https://github.com/vim-jp/vimdoc-ja/tree/pi_netrw) ブランチにpushしました。

**Comment by mattn** [comment]
@tyru thx

**Comment by tyru** [comment]
`pi_netrw.jax`なんですが、残すは `*netrw-history*` と `*netrw-todo*` と `*netrw-credits*` になりました。
一応確認なのですが、上記の項目も翻訳の対象ですよね？

**Comment by koron** [comment]
history & todoは不要だと思います。creditはどっちでも良いかな。

**Comment by koron** [comment]
historyは今回の原文の差分からもわかるんですが、どんどん古いのが消えていきます。
todoもたぶん同様かと。

creditは翻訳しづらくないですか?

**Comment by tyru** [comment]
ですね。色んな意味で訳しづらいです…

**Comment by koron** [comment]
@tyru では、現状で完成ってことで良いですかね?

**Comment by tyru** [comment]
すみません、未訳の部分が残ってました。

1. [x] `git diff f8de019^ f8de019 -- doc/pi_netrw.jax` の全ての差分を見て未訳がないかチェック
1. [x] コードブロックの始まりの`>`を削除してしまっていた部分があったので、1の差分の全てのコードブロックを再チェック
1. [x] 一部ですます調になっていない部分があったので、自分のこれまでのコミットを再度チェック
1. [x] 目次や関連項目等ではですます調は使われていないので、前後の文に合わせる (4と同時にチェック)
  - ただ `*g:netrw_altfile*` で始まるオプション変数の部分では既存の翻訳分が統一されていなかったので、その部分では基本的に私の翻訳分ではですます調を使うようにしました。
1. [x] 先頭の作者メールアドレスの部分「(まずメールアドレスから NOSPAM を削除してください)」を翻訳

をやりました。
少なくとも未訳とですます調が揃ってない部分に関してはもう無いはずです。

@koron
また、`\<or\>`で検索してみると既存の翻訳部分に未訳あるいはあえて残してある「or」がいくつかヒットします。
これらに対してはどうすべきでしょうか？

**Comment by koron** [comment]
とりあえず、もとからあったのは残して別件としましょう。(いまは1194へのキャッチアップなので)

新規分の `or` に関しては、どうするかはお任せします。

**Comment by tyru** [comment]
了解です。では `pi_netrw.jax` は完了で大丈夫です。

**Comment by koron** [comment]
@tyru PR ｵﾅｼｬｽ!

**Comment by tyru** [comment]
@koron ~~だし巻き卵~~ 出しました！ #207

**Comment by tyru** [comment]
`doc/pi_netrw.jax`と`doc/usr_02.jax`の残りは翻訳したので、
`doc/spell.jax`に関しては #65 でやる事にすれば、レビューや修正してそろそろクローズできそうです。

**Comment by tyru** [comment]
ちなみに今それぞれのブランチがbuild failedになってる原因がよく分かってないです…
(`Rakefile not found`とか出てるけど…)

**Comment by koron** [comment]
.travis.yml がないので、rubyプロジェクトと誤判定されてビルドできずに失敗しています。

**Comment by tyru** [comment]
なるほどです。
(FYI: 確かTravisの設定画面に .travis.yml がない場合はビルドを実行しないという項目があったような)

**Comment by koron** [comment]
@tyru thx! 設定しました。

**Comment by nakinor** [comment]
すみません、「タスク」のラベル剥がしちゃってたみたいです……
うちのマシン、コメントが50超えるとページ表示するのがものすごく遅くなるので……(言い訳)

**Comment by koron** [comment]
all completed.  thank you all! :tada: :birthday:

**Comment by rhysd** [comment]
:tada:

**Comment by tyru** [comment]
:+1:

**Comment by mattn** [comment]
やったー！みなさんお疲れ様でした。
